//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSOutreach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.EventInstructors = new HashSet<EventInstructor>();
            this.StudentEvents = new HashSet<StudentEvent>();
        }
    
        public int EventId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int EventTypeId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int CourseId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<EventInstructor> EventInstructors { get; set; }
        public virtual ICollection<StudentEvent> StudentEvents { get; set; }
        public virtual EventType EventType { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
