//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSOutreach
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraWork
    {
        public int ExtraWorkId { get; set; }
        public int InstructorId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string Description { get; set; }
        public Nullable<int> Miles { get; set; }
        public string Comment { get; set; }
    
        public virtual Instructor Instructor { get; set; }
    }
}
