//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSOutreach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Familiar
    {
        public int FamiliarId { get; set; }
        public int InstructorId { get; set; }
        public int SkillSetId { get; set; }
    
        public virtual Instructor Instructor { get; set; }
        public virtual SkillSet SkillSet { get; set; }
    }
}
