//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSOutreach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        public Instructor()
        {
            this.EventInstructors = new HashSet<EventInstructor>();
            this.ExtraWorks = new HashSet<ExtraWork>();
            this.Familiars = new HashSet<Familiar>();
            this.InstructorAcademics = new HashSet<InstructorAcademic>();
            this.InstructorCourses = new HashSet<InstructorCourse>();
        }
    
        public int InstructorId { get; set; }
        public int PersonId { get; set; }
        public bool canTeach { get; set; }
    
        public virtual ICollection<EventInstructor> EventInstructors { get; set; }
        public virtual ICollection<ExtraWork> ExtraWorks { get; set; }
        public virtual ICollection<Familiar> Familiars { get; set; }
        public virtual ICollection<InstructorAcademic> InstructorAcademics { get; set; }
        public virtual ICollection<InstructorCourse> InstructorCourses { get; set; }
        public virtual Person Person { get; set; }
    }
}
