//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSOutreach
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseCSOutreachEntities : DbContext
    {
        public DatabaseCSOutreachEntities()
            : base("name=DatabaseCSOutreachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Academic> Academics { get; set; }
        public DbSet<Course> Courses { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<EventInstructor> EventInstructors { get; set; }
        public DbSet<EventType> EventTypes { get; set; }
        public DbSet<ExtraWork> ExtraWorks { get; set; }
        public DbSet<Familiar> Familiars { get; set; }
        public DbSet<Instructor> Instructors { get; set; }
        public DbSet<InstructorAcademic> InstructorAcademics { get; set; }
        public DbSet<InstructorCourse> InstructorCourses { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<SkillSet> SkillSets { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<StudentEvent> StudentEvents { get; set; }
    }
}
