//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSOutreach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.StudentEvents = new HashSet<StudentEvent>();
        }
    
        public int StudentId { get; set; }
        public int PersonId { get; set; }
        public string EmergencyName { get; set; }
        public string EmergencyNumber { get; set; }
        public string EmergencyRelation { get; set; }
        public bool IsPaperWorkComplete { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<StudentEvent> StudentEvents { get; set; }
    }
}
